//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   7f= 
        ///80=A
        ///81=B
        ///82=C
        ///83=D
        ///84=E
        ///85=F
        ///86=G
        ///87=H
        ///88=I
        ///89=J
        ///8a=K
        ///8b=L
        ///8c=M
        ///8d=N
        ///8e=O
        ///8f=P
        ///90=Q
        ///91=R
        ///92=S
        ///93=T
        ///94=U
        ///95=V
        ///96=W
        ///97=X
        ///98=Y
        ///99=Z
        ///a0=a
        ///a1=b
        ///a2=c
        ///a3=d
        ///a4=e
        ///a5=f
        ///a6=g
        ///a7=h
        ///a8=i
        ///a9=j
        ///aa=k
        ///ab=l
        ///ac=m
        ///ad=n
        ///ae=o
        ///af=p
        ///b0=q
        ///b1=r
        ///b2=s
        ///b3=t
        ///b4=u
        ///b5=v
        ///b6=w
        ///b7=x
        ///b8=y
        ///b9=z
        ///e3=―
        ///e6=？
        ///e7=！
        ///e8=．
        ///e9=＆
        ///ef=♂
        ///f5=♀
        ///f6=0
        ///f7=1
        ///f8=2
        ///f9=3
        ///fa=4
        ///fb=5
        ///fc=6
        ///fd=7
        ///fe=8
        ///ff=9
        ///0101=가
        ///0102=각
        ///0103=간
        ///0104=갇
        ///0105=갈
        ///0106=갉
        ///0107=갊
        ///0108=감
        ///0109=갑
        ///010a=값
        ///010b=갓
        ///010c[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Charmap {
            get {
                return ResourceManager.GetString("Charmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   00 - 없음
        ///01 - HP 회복
        ///02 - ?
        ///03 - HP 회복 (개수 소모 없음)
        ///04 - ?
        ///05 - ?
        ///06 - PP 회복
        ///07 - ?
        ///08 - 야생 포켓몬과 만날 확률 낮아짐
        ///09 - ?
        ///0A - 독상태 회복
        ///0B - 얼음상태 회복
        ///0C - 화상상태 회복
        ///0D - 잠듦상태 회복
        ///0E - 마비상태 회복
        ///0F - 모든 상태이상 회복
        ///10 - 혼란상태 회복
        ///11 - ?
        ///12 - ?
        ///13 - ?
        ///14 - ?
        ///15 - ?
        ///16 - ?
        ///17 - ?
        ///18 - ?
        ///19 - ?
        ///1A - ?
        ///1B - ?
        ///1C - ?
        ///1D - ?
        ///1E - ?
        ///1F - ?
        ///20 - ?
        ///21 - ?
        ///22 - ?
        ///23 - ?
        ///24 - ?
        ///25 - ?
        ///26 - ?
        ///27 - ?
        ///28 - ?
        ///29 - ?
        ///2A - 메타몽의 방어력 상승
        ///2B - ?
        ///2C - ?
        ///2D - ?
        ///2E - ?
        ///2F - ?
        ///30 - ?
        ///31 - ?
        ///32 - 노말 타입 기술 위력 상[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GiveItemEffects {
            get {
                return ResourceManager.GetString("GiveItemEffects", resourceCulture);
            }
        }
    }
}
